#!/usr/bin/env bash
set -ex

# This is the master script for the capsule. When you click "Reproducible Run", the code in this file will execute.
matlab -nodisplay -r "addpath(genpath('.')); Six_alternatives_complete_run"

# The previous version of this file was commented-out and follows below:
#
# matlab -nodisplay -r "addpath(genpath('.')); Six_alternatives_grouped_run"
# 
# # The previous version of this file was commented-out and follows below:
# #
# # matlab -nodisplay -r "addpath(genpath('.')); Six_alternatives_complete_run"
# # 
# # # The previous version of this file was commented-out and follows below:
# # #
# # # matlab -nodisplay -r "addpath(genpath('.')); Six_ alternatives_complete_run"
# # # 
# # # # The previous version of this file was commented-out and follows below:
# # # #
# # # # matlab -nodisplay -r "addpath(genpath('.')); %Six alternatives - complete run"
# # # # 
# # # # # The previous version of this file was commented-out and follows below:
# # # # #
# # # # # matlab -nodisplay -r "addpath(genpath('.')); Six alternatives - complete run"
# # # # # 
# # # # # # The previous version of this file was commented-out and follows below:
# # # # # #
# # # # # # echo "Sorry, we couldn't automatically determine the right command for this file type. Please replace this line with a command to run ''Six alternatives - complete run.docx''."
# # # # # # 
# # # # # # # The previous version of this file was commented-out and follows below:
# # # # # # #
# # # # # # # echo "Sorry, we couldn't automatically determine the right command for this file type. Please replace this line with a command to run ''Six alternatives - complete run.docx''."
# # # # # # # 
# # # # # # # # The previous version of this file was commented-out and follows below:
# # # # # # # #
# # # # # # # # echo "Sorry, we couldn't automatically determine the right command for this file type. Please replace this line with a command to run ''Six alternatives.docx''."
# # # # # # # # 
# # # # # # # 
# # # # # # 
# # # # # 
# # # # 
# # # 
# # 
# 
